### ISSUE TITLE
Платформы: сценарий генерации

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Doodle-jump#23]
Продумать, каким образом будет происходить генерация новых платформ и их удаление. Все идеи можно записать здесь

Удаление: если платформа находится под экраном, она должны быть удалена.

**Comment by qwickq** [comment]
Всего на экране в один момент должно быть 6 платформы. В самом начале игры будут только <<обычные платформы>>, но каждые 12 платформ будет появляться <<платформа-трамплин>> или <<платформа-пружинка>>,они не будут влиять на количество платформ в один момент. Также спустя некоторое время игры будет уменьшаться количество платформ в один момент до 5 платформ - 4 - 3 - 2, в зависимости от протяжение игры . После того как одна из платформ зайдет за границу экрана она должна быть удалена для более хорошей оптимизации игры.
