### ISSUE TITLE
Игрок прямо под платформой

### ISSUE THREAD

**Issue by Zener085** [Zeneriode/Doodle-jump#27]
Прямо сейчас игрок, если оказывается под платформой, просто врезается в неё и падает вниз. Нужно придумать, что делать в такой ситуации. Логику программы лучше записать в комментарии под этим заданием

**Comment by qwickq** [comment]
Стоит сделать так чтобы во время прыжка героя платформа была прозрачной а когда герой находится выше той или иной платформы  становилась полноценной (не прозрачной)
